services:

  api:
    build:
      context: .
      dockerfile: bassoon-api/Dockerfile
    container_name: bassoon-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - bassoon
    restart: unless-stopped

  ui:
    build:
      context: bassoon-ui
      dockerfile: Dockerfile
    container_name: bassoon-ui
    ports:
      - "3000:80"
    networks:
      - bassoon
    depends_on:
      - api
    restart: unless-stopped

networks:
  bassoon:
    driver: bridge
